services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/liv/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  coo-svc:
    image: azorawski/coo-svc:latest
    build:
      context: .
      dockerfile: Services/CooService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__PostgresDbConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=CooService
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7001:80
    depends_on:
      - postgres
      - mongodb
      - rabbitmq
  comments-svc:
    image: azorawski/comments-svc:latest
    build:
      context: .
      dockerfile: Services/CommentsService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__PostgresDbConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=CommentsService
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7002:80
    depends_on:
      - postgres
      - mongodb
      - rabbitmq
  files-svc:
    image: azorawski/files-svc:latest
    build:
      context: .
      dockerfile: Services/FilesService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__PostgresDbConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=FilesService
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7004:80
    depends_on:
      - postgres
      - mongodb
      - rabbitmq
  gateway-svc:
    image: azorawski/gateway-svc:latest
    build:
      context: .
      dockerfile: Services/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 6001:80
  likes-svc:
    image: azorawski/likes-svc:latest
    build:
      context: .
      dockerfile: Services/LikeService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__PostgresDbConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=LikesService
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7003:80
    depends_on:
      - postgres
      - mongodb
      - rabbitmq
  identity-svc:
    image: azorawski/identity-svc:latest
    build:
      context: .
      dockerfile: Services/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
    ports:
      - 5000:80
    depends_on:
      - postgres
  profiles-svc:
    image: azorawski/profiles-svc:latest
    build:
      context: .
      dockerfile: Services/UserProfileService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7005:80
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  pgdata:
  mongodata: